### ISSUE TITLE
Database connection error while yarn dev

### ISSUE THREAD

**Issue by shohan-ch** [xtareq/ex-ts-start#1]
error: undefined {"name":"SequelizeConnectionError","original":{"code":"ER_CANNOT_RETRIEVE_RSA_KEY","errno":45044,"fatal":true,"sql":null,"sqlState":"08S01","text":"RSA public key is not available client side. Either set option `cachingRsaPublicKey` to indicate public key path, or allow public key retrieval with option `allowPublicKeyRetrieval`"},"parent":{"code":"ER_CANNOT_RETRIEVE_RSA_KEY","errno":45044,"fatal":true,"sql":null,"sqlState":"08S01","text":"RSA public key is not available client side. Either set option `cachingRsaPublicKey` to indicate public key path, or allow public key retrieval with option `allowPublicKeyRetrieval`"}}

**Comment by xtareq** [comment]
I'm using mariadb as default . So all you've to do install mysql
npm install mysql # yarn add mysql

then update database config dilect mariadb to mysql
